apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: backend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: backend
          image: gcr.io/focal-gamma-228403/backend
          ports:
            - containerPort: 2091
