version: '3.7'

services:
  api:
    container_name: api
    image: node:10-stretch
    volumes:
      - .:/usr/app:rw
      - node_modules:/app/node_modules
    networks:
      - api-network
    ports:
      - 2091:2091
    working_dir: /usr/app

networks:
  api-network:
    name: api-network
    driver: bridge

volumes:
  node_modules:
