apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 2091
      name: backend
  selector:
    app: backend
    tier: frontend
